#!/bin/bash
#
# read-menu:a menu driven system information program

clear
echo
"
Please select:
    1. Display System information
    2. Display Disk Space
    3. Display Home Space Utilization
    0. Quit
"
read -p "Enter selection [0-3] >"

if [[ $REPLY =~ ^[0-3]$ ]]
  if [[ $REPLY == 0 ]]; then
      echo "Program terminated."
      exit
  fi
  if [[ $REPLY == 1 ]]; then
     echo "Hostname: $HOSTNAME"
     uptime
     exit
  fi
  if [[ $REPLY == 2 ]]; then
     df -h
     exit
  fi
  if [[ $REPLY == 3 ]]; then
      if [[ $(id -u) -eq 0 ]]; then
         echo "Home Space Utilization (All Users)"
         du -sh /home/*
      fi
      else
         echo "Home Space Utilization ($USER)"
         du -sh $Home
      fi
      exit
  fi
else
    echo "Invalid entry. "
    exit 1
fi
