#!/bin/bash
#
#
echo "Enter a number: "
read number1
echo "Enter another number: "
read number2
#
if [ $number1 -gt 100 -o $number1 -lt 1 ]; then
  echo "$number1 is bigger than 100"
  exit 1
fi
if [ $number2 -gt 100 -o $number2 -lt 1 ]; then
  echo "$number2 is bigger than 100"
  exit 1
fi
let sum=$number1+$number2
let prod=$number1*$number2
##
if [ $sum -eq $prod ]; then
  echo "Congratulations, sum:$sum = prod:$prod"
fi
echo "Sum:  $number1 + $number2 = $sum"
echo "Product:  $number1 x $number2 = $prod"
