#!/bin/bash
#################################
#################################
echo Enter a number
read number1
echo Enter another number
read number2
###############################################
###############################################
###############################################
let sum=$number1+number2
let prod=$number1*number2
###############################################
echo sum: $number1 + $number2 = $sum
echo product: $number1 x $number2 = $prod
