#!/bin/bash
#
#
echo The first argument is $1
echo The second argument is $2
echo The third argument is $3
#
#
echo \$ $$ PID of the script
echo \# $# count arguments
echo \? last return code
echo \* $* all the arguments
