#!/bin/bash
#
#
echo the first argument is $1
echo the second argument is $2
echo the third argument is $3
#############
echo \$ $$ PID of the script
echo \# $# count arguments
echo \? $? last return code
echo \* $* all the arguments
#
#
